// Autogenerated from Pigeon (v9.2.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package io.flutter.plugins;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Pigeon {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<Object>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class StrctSrc {
    private @Nullable Long a;

    public @Nullable Long getA() {
      return a;
    }

    public void setA(@Nullable Long setterArg) {
      this.a = setterArg;
    }

    private @Nullable Long b;

    public @Nullable Long getB() {
      return b;
    }

    public void setB(@Nullable Long setterArg) {
      this.b = setterArg;
    }

    public static final class Builder {

      private @Nullable Long a;

      public @NonNull Builder setA(@Nullable Long setterArg) {
        this.a = setterArg;
        return this;
      }

      private @Nullable Long b;

      public @NonNull Builder setB(@Nullable Long setterArg) {
        this.b = setterArg;
        return this;
      }

      public @NonNull StrctSrc build() {
        StrctSrc pigeonReturn = new StrctSrc();
        pigeonReturn.setA(a);
        pigeonReturn.setB(b);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<Object>(2);
      toListResult.add(a);
      toListResult.add(b);
      return toListResult;
    }

    static @NonNull StrctSrc fromList(@NonNull ArrayList<Object> list) {
      StrctSrc pigeonResult = new StrctSrc();
      Object a = list.get(0);
      pigeonResult.setA((a == null) ? null : ((a instanceof Integer) ? (Integer) a : (Long) a));
      Object b = list.get(1);
      pigeonResult.setB((b == null) ? null : ((b instanceof Integer) ? (Integer) b : (Long) b));
      return pigeonResult;
    }
  }

  private static class JavaApiCodec extends StandardMessageCodec {
    public static final JavaApiCodec INSTANCE = new JavaApiCodec();

    private JavaApiCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 128:
          return StrctSrc.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof StrctSrc) {
        stream.write(128);
        writeValue(stream, ((StrctSrc) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface JavaApi {

    @Nullable 
    Long sum(@NonNull StrctSrc src);

    /** The codec used by JavaApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return JavaApiCodec.INSTANCE;
    }
    /**Sets up an instance of `JavaApi` to handle messages through the `binaryMessenger`. */
    static void setup(@NonNull BinaryMessenger binaryMessenger, @Nullable JavaApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.JavaApi.sum", getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<Object>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                StrctSrc srcArg = (StrctSrc) args.get(0);
                try {
                  Long output = api.sum(srcArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  ArrayList<Object> wrappedError = wrapError(exception);
                  wrapped = wrappedError;
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
