// Autogenerated from Pigeon (v9.2.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class StrctSrc;

@interface StrctSrc : NSObject
+ (instancetype)makeWithA:(nullable NSNumber *)a
    b:(nullable NSNumber *)b;
@property(nonatomic, strong, nullable) NSNumber * a;
@property(nonatomic, strong, nullable) NSNumber * b;
@end

/// The codec used by JavaApi.
NSObject<FlutterMessageCodec> *JavaApiGetCodec(void);

@protocol JavaApi
- (nullable NSNumber *)sumSrc:(StrctSrc *)src error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void JavaApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<JavaApi> *_Nullable api);

NS_ASSUME_NONNULL_END
